# Generated by Django 5.2.8 on 2025-11-15 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_profile_old_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='old_cart',
        ),
    ]
