# Generated by Django 5.2.8 on 2025-11-10 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_trademark_product_trademark'),
    ]

    operations = [
    ]
