[build]
builder = "nixpacks"
buildCommand = "chmod +x build.sh && ./build.sh"

[deploy]
startCommand = "gunicorn ecom.wsgi:application --bind 0.0.0.0:$PORT"

[nixpacks]
# S'assurer que manage.py est accessible
cmds = ["python manage.py migrate --no-input"]