# Generated by Django 5.2.8 on 2025-12-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_purchasehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasehistory',
            name='purchase_success',
            field=models.BooleanField(default=False),
        ),
    ]
