# Generated by Django 5.2.8 on 2025-12-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_purchasehistory_purchase_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasehistory',
            name='stripe_session_id',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
