# Generated by Django 5.2.8 on 2025-12-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_purchasehistory_stripe_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasehistory',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
